sudo chgrp -R www-data simulator/mesh_gen/geo
sudo chmod -R g+w ...
sudo chgrp -R www-data simulator/mesh_gen/vol
sudo chmod -R g+w ...
sudo chgrp -R www-data simulator/mesh
sudo chmod -R g+w ...
sudo chgrp -R www-data simulator/config
sudo chmod -R g+w ...
sudo chgrp -R www-data static/model
sudo chmod -R g+w ...
sudo chgrp -R www-data simulator/result
sudo chmod -R g+w ...
sudo chgrp -R www-data docker_simulator/config
sudo chmod -R g+w ...
sudo chgrp -R www-data docker_simulator/pool
sudo chmod -R g+w ...


