#!/bin/bash

MESHGEN_DIR=${1}
MODEL_NAME=${2}
MODEL_CONFIG_PATH=${PROJECT_DIR}/${3}
MODEL_GEO_PATH=${PROJECT_DIR}/${MESHGEN_DIR}geo/${MODEL_NAME}.geo
MODEL_VOL_PATH=${PROJECT_DIR}/${MESHGEN_DIR}vol/${MODEL_NAME}.vol
MODEL_MESH_PATH=${PROJECT_DIR}/${4}

mkdir ${MESHGEN_DIR}geo/
mkdir ${MESHGEN_DIR}vol/

#CONFIG_PATH=${PROJECT_PATH}/simulator/config
#MESH_PATH=${PROJECT_PATH}/simulator/mesh
#MESHGEN_PATH=${PROJECT_PATH}/simulator/mesh_gen

#MODEL_NAME=${1}
#GEO_CONFIG_PATH=${CONFIG_PATH}/${MODEL_NAME}.txt
#GEO_PATH=${MESHGEN_PATH}/geo/${MODEL_NAME}.geo
#VOL_PATH=${MESHGEN_PATH}/vol/${MODEL_NAME}.vol
#VTK_PATH=${MESH_PATH}/${MODEL_NAME}.vtk

${MESHGEN_DIR}geo_gen ${MODEL_CONFIG_PATH} ${MODEL_GEO_PATH}
netgen -geofile=${MODEL_GEO_PATH} -meshfile=${MODEL_VOL_PATH} -batchmode
${MESHGEN_DIR}vol2vtk ${MODEL_VOL_PATH} ${MODEL_MESH_PATH}

